image: gcc:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Installing cmake..."
    - apt-get update --yes
    - apt-get install --yes cmake
    - echo "Compiling the code..."
    - make
    - echo "Compile complete."
  artifacts:
    paths:
      [todo]

execute:
  stage: test
  script:
    - echo "Executing todo..."
    - ./todo
    - echo "Code successfully executed..."

leak-test:
  stage: test
  only:
    changes:
      - "ToDoList/**/**"
  script:
    - echo "Installing valgrind..."
    - apt-get update -y
    - apt-get install valgrind -y
    - echo "Executing valgrind..."
    - valgrind --leak-check=yes --error-exitcode=1 --log-file="log" ./todo
  artifacts:
    paths:
      [log]

build-unit-tests:
  stage: test
  only:
    changes:
      - "ToDoList/**/**"
  trigger:
    include: "pipelines/tests-ci.yml"

analyze-code:
  stage: test
  only:
    changes:
      - "ToDoList/**/**"
  trigger:
    include: "pipelines/checkcpp-ci.yml"

generate-doxygen:
  stage: deploy
  when: on_success
  only:
    changes:
      - "ToDoList/**/**"
  trigger:
    include: "pipelines/doxygen-ci.yml"

deploy-application: 
  stage: deploy
  when: on_success
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."