image: gcc:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Installing cmake..."
    - apt-get update --yes
    - apt-get install --yes cmake
    - echo "Compiling the code..."
    - make
    - echo "Compile complete."
  artifacts:
    paths:
      [todo]

execute:
  stage: test
  script:
    - echo "Executing todo..."
    - ./todo
    - echo "Code successfully executed..."

leak-test:
  stage: test
  script:
    - echo "Installing valgrind..."
    - apt-get update -y
    - apt-get install valgrind -y
    - echo "Executing valgrind..."
    - valgrind --leak-check=yes --error-exitcode=1 --log-file="log" ./todo
  artifacts:
    paths:
      [log]

build-unit-tests:
  stage: test
  trigger:
    include: "pipelines/tests-ci.yml"

analyze-code:
  stage: test
  trigger:
    include: "pipelines/checkcpp-ci.yml"

generate-doxygen:
  stage: deploy
  trigger:
    include: "pipelines/doxygen-ci.yml"

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - mv tests_logs/*.log public
  artifacts:
    paths:
      - public

deploy-job: 
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."