image: gcc:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Installing cmake..."
    - sudo apt-get update -y
    - sudo apt-get install cmake -y 
    - echo "Compiling the code..."
    - make
    - echo "Compile complete."
  artifacts:
    paths:
      - todo
      - ToDoList/build

execute:
  stage: test
  script:
    - echo "Executing todo..."
    - ./todo
    - echo "Code successfully executed..."

generate-doxygen:
  stage: deploy
  when: on_success
  trigger:
    include: "pipelines/doxygen-ci.yml"

deploy-application: 
  stage: deploy
  when: on_success
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
