image: gcc:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Installing cmake..."
    - apt-get update -y
    - apt-get install cmake -y 
    - echo "Compiling the code..."
    - make
    - echo "Compile complete."
  artifacts:
    expose_as: 'Executable'
    expire_in: 1 week
    paths:
      - todo
      - ToDoList/build

execute:
  stage: test
  needs:
    - job: build
  script:
    - echo "Executing todo..."
    - ./todo
    - echo "Code successfully executed..."

leak-test:
  stage: test
  needs:
    - job: build
  only:
    changes:
      - "ToDoList/**/**"
      - "pipelines/**"
      - .gitlab-ci.yml
  script:
    - echo "Installing valgrind..."
    - apt-get update -y
    - apt-get install valgrind -y
    - echo "Executing valgrind..."
    - valgrind --leak-check=yes --error-exitcode=1 --log-file="log" ./todo
  artifacts:
    expose_as: 'Leak Test'
    expire_in: 1 hrs
    paths:
      [log]

build-unit-tests:
  stage: test
  needs:
    - job: build
  only:
    changes:
      - "ToDoList/**/**"
      - "pipelines/**"
      - .gitlab-ci.yml
  trigger:
    include: "pipelines/tests-ci.yml"

lint-test:
  stage: test
  needs:
    - job: build
      artifacts: true
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /fix|feat/i
      - $CI_COMMIT_REF_NAME =~ /features/i
  trigger:
    include: "pipelines/linter-ci.yml" 
    strategy: depend

  
analyze-code:
  stage: test
  needs:
    - job: build
  only:
    changes:
      - "ToDoList/**/**"
      - "pipelines/**"
      - .gitlab-ci.yml
  trigger:
    include: "pipelines/checkcpp-ci.yml"

generate-doxygen:
  stage: deploy
  needs:
    - job: execute
    - job: leak-test
    - job: build-unit-tests
    - job: lint-test
    - job: analyze-code
  when: on_success
  only:
    changes:
      - "ToDoList/**/**"
      - "pipelines/**"
      - .gitlab-ci.yml
  trigger:
    include: "pipelines/doxygen-ci.yml"

deploy-application: 
  stage: deploy
  needs:
    - job: execute
    - job: leak-test
    - job: build-unit-tests
    - job: lint-test
    - job: analyze-code
  when: on_success
  trigger:
    include: "pipelines/executable-ci.yml"