image: gcc:latest

stages:
  - build
  - test
  - doxygen
  - deploy

build:
  stage: build
  script:
    - echo "Installing cmake..."
    - apt-get update --yes
    - apt-get install --yes cmake
    - echo "Compiling the code..."
    - make
    - echo "Compile complete."
  artifacts:
    paths:
      [ToDoList/todo]

execute:
  stage: test
  script:
    - echo "Executing todo..."
    - ./todo
    - echo "Code successfully executed..."

leak-test:
  stage: test
  script:
    - echo "Installing valgrind..."
    - apt-get update -y
    - apt-get install valgrind -y
    - echo "Executing valgrind..."
    - valgrind --leak-check=yes --error-exitcode=1 --log-file="log" ./todo
  artifacts:
    paths:
      [ToDoList/log]

generate-doxygen:
  stage: doxygen
  trigger:
    include: "pipelines/doxygen-ci.yml"
  only:
    - master


deploy-job: 
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."