image: gcc:latest

stages:
  - generate_doxygen

variables:
  DOXYGEN_DIR: "docs"

generate_doxygen:
  stage: generate_doxygen
  script:
    - apt-get update -qy
    - apt-get install -y doxygen
    - echo "Generating Doxyfile..."
    - doxygen Doxyfile
    - echo "Successfully generated Doxyfile !"
  artifacts:
    expose_as: 'Documentation'
    expire_in: 1 week
    paths:
      - $DOXYGEN_DIR