image: gcc:latest

stages:
  - generate_executable

generate_executable:
  stage: generate_executable
  script:
    - apt-get update -y
    - apt-get install -y cmake
    - echo "Generating debian executable..."
    - cmake .
    - cd ToDoList
    - cmake — build .
    - cpack
    - echo "Successfully generated debian executable !"