image: gcc:latest

stages:
  - lint

clang-tidy:
  stage: lint
  script:
    - echo "Running clang-tidy..."
    - sudo apt-get update -y
    - sudo apt-get install -y clang-tidy 
    - clang-tidy -p ToDoList/build -checks='*' ToDoList/src/**/*.cpp 2>&1 | tee clang-tidy-reports/linter-report.txt
    - CLANG_TIDY_EXIT_CODE=$?
    - if [ $CLANG_TIDY_EXIT_CODE -ne 0 ]; then
        echo "clang-tidy found issues - failing the job";
        exit 1;
      else
        echo "No clang-tidy issues found";
      fi
  artifacts:
    paths:
      - clang-tidy-reports/
